# ICT PLATFORM
# Build your Angular project and run tests with Karma.
# Author: Hoangl

trigger:
  branches:
    include:
    - dev
    - staging
    - releases/*
    exclude:
    - releases/old*

pool:
  name: AgentPool

variables:
- group: k8s-ci-variable

steps:
#- task: npmAuthenticate@0
#  displayName: 'npm Authenticate .npmrc'
#  inputs:
#    workingFile: .npmrc
#    customEndpoint: 'GitHub Registry'
- task: Docker@2
  displayName: Login to registry.evn.com.vn
  inputs:
    command: login
    containerRegistry: HarbourRegistryConnection1
- task: Docker@2
  displayName: Build and Push Image
  inputs:
    command: buildAndPush
    repository: $(ENV)/$(IMAGE)
    containerRegistry: HarbourRegistryConnection1
    tags: $(TAG)
